### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by jeonghwaYoo** [1ytic/warp-rnnt#11]
OS: Windows
CUDA_toolkit: 10.1
Python: 3.7
Framework : tensorflow-gpu (1.15.4), pytorch(1.7.0)

Hello. Thank you for your projects

When I try install this module, I got error message. 
`pip install warp_rnnt`

> CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

> Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I didn't install cuda directly on my environment. My cuda is installed in anaconda virtual environment. 
 
Can't I install this module in this case?

Thank you

**Comment by jeonghwaYoo** [comment]
After install cuda 10.1 on my local environment. 
That error message doesn't show. 
However, other message was displayed.

>Building wheels for collected packages: warp-rnnt, future
  Running setup.py bdist_wheel for warp-rnnt ... error
  Complete output from command C:\Users\2020498\Anaconda3\envs\warp\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\2020498\\AppData\\Local\\Temp\\pip-install-rb_4j1ib\\warp-rnnt\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\2020498\AppData\Local\Temp\pip-wheel-5f4kp887 --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.5
  creating build\lib.win-amd64-3.5\warp_rnnt
  copying warp_rnnt\test.py -> build\lib.win-amd64-3.5\warp_rnnt
  copying warp_rnnt\__init__.py -> build\lib.win-amd64-3.5\warp_rnnt
  running build_ext
  C:\Users\2020498\Anaconda3\envs\warp\lib\site-packages\torch\utils\cpp_extension.py:238: UserWarning: Error checking compiler version for cl: [WinError 2] 지정된 파일을 찾을 수 없습니다 (
The specified file could not be found)
    warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
  building 'warp_rnnt._C' extension
  creating C:\Users\2020498\AppData\Local\Temp\pip-install-rb_4j1ib\warp-rnnt\build\temp.win-amd64-3.5
  creating C:\Users\2020498\AppData\Local\Temp\pip-install-rb_4j1ib\warp-rnnt\build\temp.win-amd64-3.5\Release
  Emitting ninja build file C:\Users\2020498\AppData\Local\Temp\pip-install-rb_4j1ib\warp-rnnt\build\temp.win-amd64-3.5\Release\build.ninja...
  Compiling objects...
  Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
  [1/3] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -IC:\Users\2020498\Anaconda3\envs\warp\lib\site-packages\torch\include -IC:\Users\2020498\Anaconda3\envs\warp\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\2020498\Anaconda3\envs\warp\lib\site-packages\torch\include\TH -IC:\Users\2020498\Anaconda3\envs\warp\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -IC:\Users\2020498\Anaconda3\envs\warp\include -IC:\Users\2020498\Anaconda3\envs\warp\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" -c C:\Users\2020498\AppData\Local\Temp\pip-install-rb_4j1ib\warp-rnnt\binding.cpp /FoC:\Users\2020498\AppData\Local\Temp\pip-install-rb_4j1ib\warp-rnnt\build\temp.win-amd64-3.5\Release\binding.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
  FAILED: C:/Users/2020498/AppData/Local/Temp/pip-install-rb_4j1ib/warp-rnnt/build/temp.win-amd64-3.5/Release/binding.obj
  cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -IC:\Users\2020498\Anaconda3\envs\warp\lib\site-packages\torch\include -IC:\Users\2020498\Anaconda3\envs\warp\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\2020498\Anaconda3\envs\warp\lib\site-packages\torch\include\TH -IC:\Users\2020498\Anaconda3\envs\warp\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -IC:\Users\2020498\Anaconda3\envs\warp\include -IC:\Users\2020498\Anaconda3\envs\warp\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" -c C:\Users\2020498\AppData\Local\Temp\pip-install-rb_4j1ib\warp-rnnt\binding.cpp /FoC:\Users\2020498\AppData\Local\Temp\pip-install-rb_4j1ib\warp-rnnt\build\temp.win-amd64-3.5\Release\binding.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
  CreateProcess failed: The system cannot find the file specified.
  ninja: fatal: ReadFile: 핸들이 잘못되었습니다. (
The handle is invalid.)

  Traceback (most recent call last):
    File "C:\Users\2020498\Anaconda3\envs\warp\lib\site-packages\torch\utils\cpp_extension.py", line 1423, in _run_ninja_build
      check=True)
    File "C:\Users\2020498\Anaconda3\envs\warp\lib\subprocess.py", line 398, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\2020498\AppData\Local\Temp\pip-install-rb_4j1ib\warp-rnnt\setup.py", line 62, in <module>
      "Topic :: Software Development :: Libraries :: Python Modules",
    File "C:\Users\2020498\Anaconda3\envs\warp\lib\site-packages\setuptools\__init__.py", line 140, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\2020498\Anaconda3\envs\warp\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\2020498\Anaconda3\envs\warp\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "C:\Users\2020498\Anaconda3\envs\warp\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\2020498\Anaconda3\envs\warp\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\2020498\Anaconda3\envs\warp\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\2020498\Anaconda3\envs\warp\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\2020498\Anaconda3\envs\warp\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\2020498\Anaconda3\envs\warp\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\2020498\Anaconda3\envs\warp\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\2020498\Anaconda3\envs\warp\lib\site-packages\setuptools\command\build_ext.py", line 78, in run
      _build_ext.run(self)
    File "C:\Users\2020498\Anaconda3\envs\warp\lib\distutils\command\build_ext.py", line 339, in run
      self.build_extensions()
    File "C:\Users\2020498\Anaconda3\envs\warp\lib\site-packages\torch\utils\cpp_extension.py", line 603, in build_extensions
      build_ext.build_extensions(self)
    File "C:\Users\2020498\Anaconda3\envs\warp\lib\distutils\command\build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "C:\Users\2020498\Anaconda3\envs\warp\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\2020498\Anaconda3\envs\warp\lib\site-packages\setuptools\command\build_ext.py", line 199, in build_extension
      _build_ext.build_extension(self, ext)
    File "C:\Users\2020498\Anaconda3\envs\warp\lib\distutils\command\build_ext.py", line 533, in build_extension
      depends=ext.depends)
    File "C:\Users\2020498\Anaconda3\envs\warp\lib\site-packages\torch\utils\cpp_extension.py", line 585, in win_wrap_ninja_compile
      with_cuda=with_cuda)
    File "C:\Users\2020498\Anaconda3\envs\warp\lib\site-packages\torch\utils\cpp_extension.py", line 1163, in _write_ninja_file_and_compile_objects
      error_prefix='Error compiling objects for extension')
    File "C:\Users\2020498\Anaconda3\envs\warp\lib\site-packages\torch\utils\cpp_extension.py", line 1436, in _run_ninja_build
      raise RuntimeError(message)
  RuntimeError: Error compiling objects for extension

How can I solve this problem?

**Comment by 1ytic** [comment]
Hi, @jeonghwaYoo. As you noticed, the custom CUDA-based package for pytorch depends on properly installed CUDA package in OS system. According to the second issue, unfortunately, I didn't test this package on Window system.

**Comment by jeonghwaYoo** [comment]
@1ytic Okay I got it. Thank you!
