### ISSUE TITLE
Undefined symbol when loading module

### ISSUE THREAD

**Issue by mjurkus** [1ytic/warp-rnnt#13]
Hi, I'm trying to use `warp-rnnt`, but I get the error mentioned below.
My environment:

```
Python: Python 3.7.5
Torch: 1.8.0+cu111
CUDA Version: 11.2
```

Output of `python -m warp_rnnt.test`
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/martynas/.../lib/python3.7/site-packages/warp_rnnt/__init__.py", line 2, in <module>
    import warp_rnnt._C as core
ImportError: /home/martynas/.../lib/python3.7/site-packages/warp_rnnt/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIN3c107complexIfEEEEPKNS_6detail12TypeMetaDataEv
```

Is there anything I can do?

**Comment by 1ytic** [comment]
Hi, @mjurkus 
Sorry, I didn't test this package with PyTorch 1.8

**Comment by mjurkus** [comment]
I see. I'll downgrade PyTorch then. Or is there anything else I could do?

**Comment by mjurkus** [comment]
Yeah... CUDA 10.x doesn't support the RTX 3070 GPU.

**Comment by mjurkus** [comment]
Seems to work fine with `torch==1.7.1+cu110`. Closing now.
