### ISSUE TITLE
Exception: CPU version is not implemented

### ISSUE THREAD

**Issue by yyMoming** [1ytic/warp-rnnt#17]
ERROR: Command errored out with exit status 1:
             cwd: /tmp/yangweiming/pip-install-bih20nfz/warp-rnnt_c2a512c1bf8a43c29d5d5a5f050bd56f/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/yangweiming/pip-install-bih20nfz/warp-rnnt_c2a512c1bf8a43c29d5d5a5f050bd56f/setup.py", line 48, in <module>
        raise Exception("CPU version is not implemented")
    Exception: CPU version is not implemented
    No CUDA runtime is found, using CUDA_HOME='/home/yangweiming/cuda-10.1'

**Comment by 1ytic** [comment]
Try to properly specify LD_LIBRARY_PATH.
