### ISSUE TITLE
Exception: CPU version is not implemented

### ISSUE THREAD

**Issue by iflov** [1ytic/warp-rnnt#37]
 pip install warp_rnnt    
Collecting warp_rnnt
  Using cached warp_rnnt-0.6.0.tar.gz (10 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/pn/y9dpgwpx3lddd2whnwsc256m0000gn/T/pip-install-n8iz7px8/warp-rnnt_40ff3db4b30a49339af3db950e96e47e/setup.py", line 22, in <module>
          raise Exception("CPU version is not implemented")
      Exception: CPU version is not implemented
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

I can't solve it Because I'm elementary level developer ;( 
plz help me I wan't solve this error!

**Comment by iflov** [comment]
I develop in anaconda

Python 3.8.0 (default, Nov  6 2019, 15:49:01)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/Users/hyeontaelee/opt/anaconda3/envs/my_env/lib/python38.zip', '/Users/hyeontaelee/opt/anaconda3/envs/my_env/lib/python3.8', '/Users/hyeontaelee/opt/anaconda3/envs/my_env/lib/python3.8/lib-dynload', '/Users/hyeontaelee/opt/anaconda3/envs/my_env/lib/python3.8/site-packages']

my path is here but i can't install warp_rnnt

**Comment by dewishyi** [comment]
您好，我也遇到了同样的问题，请问您这个问题解决了吗，能否分享一下您的解决方案，万分感谢
